name: LocalCore
version: '${project.version}'
author: Markus Peirleitner (Rengobli)
website: www.peirleitner.at
api-version: 1.19

main: at.peirleitner.core.SpigotMain

commands:
  core:
    usage: </command>
    description: Version output and main administration tool
  language:
    usage: </command>
    description: Language Management
    aliases: [lang, sprache]
  motd:
    usage: </command>
    description: MOTD Management
  maintenance:
    usage: </command>
    description: Maintenance Management
    aliases: [wartung, wartungen]
  license:
    usage: </command>
    description: License Management
    aliases: [licenses, lizenz, lizenzen]
  money:
    usage: </command>
    description: Display Economy of the current SaveType
    aliases: [balance]
  economy:
    usage: </command>
    description: Economy Management
    aliases: [eco]
  slot:
    usage: </command>
    description: Slots Management
    aliases: [slots]
  pay:
    usage: </command>
    description: Send money to another player