name: LocalCore
version: '${project.version}'
author: Markus Peirleitner (Rengobli)
website: www.peirleitner.at
api-version: 1.19

main: at.peirleitner.core.SpigotMain

commands:
  language:
    usage: </command>
    description: Language Management